# Generated by Django 3.1.6 on 2021-02-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='end_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='start_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
