# Generated by Django 3.1.6 on 2021-02-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20210206_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='position',
            name='start_at',
        ),
    ]
