# Generated by Django 3.1.6 on 2021-02-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20210206_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='end_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='start_at',
            field=models.DateTimeField(null=True),
        ),
    ]
