# Generated by Django 3.1.6 on 2021-02-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_auto_20210208_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='image',
            new_name='profile_pic',
        ),
    ]
